#!/usr/bin/env python
# encoding: utf-8

# Remote hardware type
REMOTE_DEVICE_PIC = 0
REMOTE_DEVICE_SIMULATOR = 1
REMOTE_DEVICE_UNKNOWN = REMOTE_DEVICE_PIC

# Host hardware type
HOST_DEVICE_ARM = 0
HOST_DEVICE_PC = 1

# Team color
TEAM_BLUE = 0
TEAM_RED  = 1
TEAM_UNKNOWN = 2

# Movement
MOVEMENT_ROTATE = 0
MOVEMENT_MOVE = 1

# Direction
DIRECTION_FORWARD = 1
DIRECTION_BACKWARD = -1

# Goto finished reason
REASON_DESTINATION_REACHED = 0
REASON_PAWN_FOUND = 1
REASON_QUEEN_FOUND = 2
REASON_KING_FOUND = 3

# Blocking side
BLOCKED_FRONT = 1
BLOCKED_BACK = -1

# Axis
AXIS_ABSCISSA = 0
AXIS_ORDINATE = 1
