#!/bin/sh
#
# Setup automatic hostname
#

case "$1" in
  start)
    echo -n "Update hostname: "
    MAC_ADDRESS=`ifconfig eth0 | head -n 1 | tail -c 20`
    if [ $MAC_ADDRESS = "00:10:75:1A:BD:45" ]; then
        hostname sheldon
        echo "OK"
    elif [ $MAC_ADDRESS = "00:10:75:1A:86:F3" ]; then
        hostname leonard
        echo "OK"
    elif [ $MAC_ADDRESS = "00:10:75:1A:87:59" ]; then
        hostname penny
        echo "OK"
    else
        echo "Unchanged"
    fi
    ;;
  stop)
    ;;
  restart|reload)
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
