#!/bin/sh
#
# Start the network....
#

CURRENT_DIR=`dirname $0`

case "$1" in
  start)
	echo "Starting network..."
	/sbin/ifup -a
    $CURRENT_DIR/start-wifi.sh
	;;
  stop)
	echo -n "Stopping network..."
	/sbin/ifdown -a
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

