#!/bin/sh
#
# Start the network....
#

case "$1" in
  start)
    echo "Starting network..."
    /sbin/ifup -a
    if [ `hostname` = "sheldon" ]; then
      ifconfig wlan0 192.168.3.10
    elif [ `hostname` = "leonard" ]; then
      ifconfig wlan0 192.168.3.11
    fi
    ;;
  stop)
    echo -n "Stopping network..."
    /sbin/ifdown -a
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?

