#!/bin/sh
#
# Start the network....
#

case "$1" in
  start)
    if [ `hostname` = "jennifer" ]; then
        echo "Starting hostapd..."
        /usr/sbin/hostapd /etc/hostapd.conf
    fi
    ;;
  stop)
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?

