#!/bin/sh
#
# Start the wifi connection daemon
#
case "$1" in
  start)
    if [ `hostname` != "jennifer" ]; then
        echo "Starting wificonnd..."
        /usr/bin/wificonnd.sh &
    fi
    ;;
  stop)
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?

