#!/bin/sh
WEB_ROOT=/root/bhware/bhbot/brewery/web
if [ ! -f "$WEB_ROOT/cgi-bin/index.cgi" ]; then
    gcc -O2 -o "$WEB_ROOT/cgi-bin/index.cgi" "$WEB_ROOT/cgi-bin/httpd_indexcgi.c"
fi
/usr/sbin/httpd -c /etc/httpd.conf
